### ISSUE TITLE
Does not handle spaces on windows when using forward slashes

### ISSUE THREAD

**Issue by ccoenen** [janfri/multi_exiftool#1]
If i give MultiExiftool a path with spaces, it will break them up into multiple paths:

``` ruby
require 'multi_exiftool'
# => true
reader = MultiExiftool::Reader.new
# => #<MultiExiftool::Reader:0x3a16b68 @exiftool_command="exiftool", @options={}, @filenames=[], @option_mapping={:numerical=>:n, :group=>:g}>
reader.tags = ['-subject']
# => ["-subject"]
reader.exiftool_command = File.join(Dir.pwd, 'exiftool')
# => "C:/tmp/exiftool"
reader.filenames = ['C:/tmp/2009-03-07 Test Path/IMG_4224.JPG']
# => ['C:/tmp/2009-03-07 Test Path/IMG_4224.JPG']
values = reader.read
# => []
reader.errors
# => ["File not found: C:/tmp/2009-03-07/", "File not found: Test/", "File not found: Path/IMG_4224.JPG"]
```

**Comment by ccoenen** [comment]
It seems that this only happens when you specify the slashes to be forward slashes.

``` ruby
reader.filenames = ["C:\tmp\2009-03-07 Test Path\IMG_4224.JPG"]
# => ["C:\tmp\x809-03-07 test PathIMG_4224.JPG"] # yes, this looks broken in my terminal, too!
reader.read
# => [#<MultiExiftool::Values:0x300ff18 @values={....
```

**Comment by ccoenen** [comment]
Funnily enough, this works fine with umlauts. It's not showing the behaviour of https://github.com/janfri/mini_exiftool/issues/22

**Comment by janfri** [comment]
In contrast to mini_exiftool in multi_exiftool I don't do anything about encoding issues. But I use `Shellwords.escape` to escape filenames which doesn't work very well on windows systems.

Maybe a better version of  `Executable#escape` will help. Have a look at https://github.com/janfri/mini_exiftool/blob/master/lib/mini_exiftool.rb#L507-515.

Good luck. Pull requests are welcome. ;-)

**Comment by ccoenen** [comment]
i have a solution where i just let popen3 figure out the escaping. Popen3 (and other commands) can take an array of strings instead of a single command.

All the tests are going haywire (**42 failures**, especially those that try to pin down the output of `command`). I didn't forget about them, I wanted to get your opinion first. The Writer will also need some work, right now that part still uses `Shellwords`. Also, i seem to be fetching all data, even if I'm specifying tags. I'm not sure if this is a regression.

The commit can be seen above. It works on windows, including spaces in filenames and umlauts. If this is something you would like to pursue, i'd get to fixing the changed situation in the tests.

**Comment by janfri** [comment]
The solution to use the Open3 escaping techniques sounds good. It seems to work on Linux with UTF-8 as LOCALE. Adapting the tests is a little bit busywork. ;-)

The problem with specifying tags is a misunderstanding: The hyphen before the command-line argument is added automatically (think tag as tag not as command-line-argument), so you have to do it this way

``` ruby
reader.tags = ['subject']
# or my preferred syntax
reader.tags = %w[author comment subject]
```

If you put a hyphen before a tag name it will end up in `exiftool --tag ...` which means that exiftool will _exclude_ this tag.

So there is no regression in this point.

**Comment by ccoenen** [comment]
Thanks for the correction regarding my tags mixup!

I will alter the tests accordingly and wrap this up as a pull request. This will probably happen over the weekend, though. One other place that has Shellwords in it is the Writer. Do you think, the popen3-escaping will be alright there, as well?

**Comment by janfri** [comment]
Yes of course, when using Open3 then everywhere.

**Comment by janfri** [comment]
Am I correct that this pull request solve the issue with spaces in filenames and/or directorynames but not the problem with umlauts?

**Comment by ccoenen** [comment]
Before this patch, paths with forward slashes _and_ spaces would get broken up around the spaces. With the patch, i can specify a path with forward or backward slashes as i please and still get the expected result. Umlauts in the path seem to have been broken as well, though i did not test that at first.

After applying this pull request, I just confirmed that i can read a file with multi_exiftool both with and without umlauts, spaces or various slashes. This works in irb or from a script with and without explicit setting of encoding in the ruby file.

I also just tested a file containing umlauts in the iptc/xmp subject, which came through just fine.

```
#<MultiExiftool::Values:0x29323e0 @values={"sourcefile"=>"C:/tmp/2009-03-07 Test Path ???/MESO_Weihnachtsfeier_030.jpg", "subject"=>["Björn  ...
```

Interesting is, that @values["sourcefile"] _is_ broken. But that would also probably deserve a different issue and pull request.

Also, **writing** is a different matter, and that's what i'm getting at with the work in progress over at https://github.com/ccoenen/multi_exiftool/commit/4b836a6d5d67d831e24e94e7276564577ca4e8ad, but i would rather create a different pull request for that.

**Comment by ccoenen** [comment]
I may have a solution that might fix spaces, encoding, writing and `@values["sourcefile"]` all at the same time. I pushed it over to this branch: https://github.com/ccoenen/multi_exiftool/tree/send-arguments-to-stdin

This breaks all of the tests once more. And before i fix them again i'd like to hear your input on this one.

The main fix is, that the arguments never hit any shell. They are piped directly into exiftools stdin via `-@ -`. So far this is very promising.

**Comment by janfri** [comment]
Sounds great. First of all: Thanks a lot for your effort!

Some thoughts:
- The `Reader#command` and `Writer#command` methods should be renamed to `exiftool_args` (this will correspond well with the `exiftool_command`method)
- The `join`in [mocking_open3](https://github.com/ccoenen/multi_exiftool/commit/416942cc6275f978d9574a0d6a62a2281def3810#diff-fa17210be88d091a513b7c0ed2cf5dafR27) is not ideal because it could not differentiate between `['exiftool', '-comment=Hallo Welt', 'file.jpg']` and `['exiftool', '-comment=Hallo', 'Welt', 'file.jpg']`; maybe there is a better solution than mocking open3 at all
- Yes, we need indeed reals tests with real files

Maybe we should discuss this points in more detail via email - in german? janfri26@gmail.com
