### ISSUE TITLE
Ruby 1.9 Support

### ISSUE THREAD

**Issue by andyjbas** [janfri/multi_exiftool#11]
[The use of keyword arguments](https://github.com/janfri/multi_exiftool/blob/master/lib/multi_exiftool.rb#L63) in `delete_values` is currently preventing use with ruby 1.9. Are you open to a PR to resolve this?

**Comment by janfri** [comment]
Do you need support for Ruby 1.9. I'm considering to drop Ruby 1.9 support.

**Comment by andyjbas** [comment]
In my case I'm working with a legacy project with a small team that isn't in a position to upgrade any time soon. I'm utilizing a fork [with changes to support 1.9](https://github.com/janfri/multi_exiftool/compare/master...andyjbas:rm_keyword_args) for now. 

In my opinion, if you have future plans that would be made more difficult by having to support 1.9, it's probably not worth continuing support. But if the code design will remain the same, you're only 1 line away. Having at least 1 version in rubygems with 1.9 support would at least give future devs of legacy projects a starting point to adapt.

**Comment by janfri** [comment]
PR will be accepted. Maybe I will drop support for Ruby 1.9 in version 1.0 of multi_exiftool.

**Comment by janfri** [comment]
@andyjbas: Just released multi_exiftool 0.15.0 with restored Ruby 1.9 support.
