### ISSUE TITLE
ArgumentError -  invalid datetime

### ISSUE THREAD

**Issue by dedekm** [janfri/multi_exiftool#14]
i'm getting `ArgumentError: argument out of range` when trying to process mp3 file.

I've found out it is caused by invalid date in `datetimeoriginal` tag - `2022:25:01 16:25` (day and month are switched)

imho this should be escaped to skip the tag or raise some custom error, because `ArgumentError` is confusing for the user

**Comment by janfri** [comment]
Would it be ok, to get the onconverted string value in this case?

**Comment by janfri** [comment]
I have just released multi_exiftool 0.17.0. In case of an invalid timestamp value now the unvonverted string value is returned. So you have the possibility to interpret this somehow. Let me know if that helps.

**Comment by dedekm** [comment]
@janfri yes, this works too. thanks
