### ISSUE TITLE
Stop on MultiExiftool.Executable.parse_errors

### ISSUE THREAD

**Issue by fitmap** [janfri/multi_exiftool#16]
I wrote a patch, then it works, but I do not known why.

module MultiExiftool
	# Mixin for Reader and Writer.
	module Executable
		def parse_errors
			if @stderr.stat.size.zero?
				@errors = []
			else
				@errors = @stderr.read.lines(chomp: true).select {|l| l =~ /^(Error|Warning):/}
			end
		end
	end
end

**Comment by janfri** [comment]
Strange. Which operation system do you use? Could you post a code example, which shows this behaviour?

**Comment by janfri** [comment]
I close this issue because I could not reproduce the problem. Feel free to reopen it if you have more information.

**Comment by janfri** [comment]
Maybe it's the same problem as #17

**Comment by janfri** [comment]
I hope it's fixed in multi_exiftool version 0.18.1. Let me know if it works for you.
