### ISSUE TITLE
Image that always freezes on read

### ISSUE THREAD

**Issue by andrewkendall** [janfri/multi_exiftool#17]
I believe I've found an image that freezes the tool every time it is read.

[a.jpg.zip](https://github.com/janfri/multi_exiftool/files/15410558/a.jpg.zip)

Steps to reproduce:

```
multi_exiftool_reader = MultiExiftool::Reader.new
multi_exiftool_reader.filenames = [Rails.root.join('a.jpg')]
multi_exiftool_reader.read
```

I inspected the image with exiftool and I imagine the cause is the huge field "Mask Group Based Corr Mask Masks Dabs".

I've never seen anything like this before, so any ideas how to avoid a freeze are welcomed.

**Comment by janfri** [comment]
It's a problem with IO buffers. I will have a look at this.

**Comment by janfri** [comment]
I hope it's fixed in multi_exiftool version 0.18.1. Let me know if it works for you.

**Comment by andrewkendall** [comment]
Perfect. That is amazing. Tested and fixed. I've been using multi_exiftool since 2010. I really appreciate it!

**Comment by janfri** [comment]
Thank you for your kind feedback.
